# Generated by Django 3.2 on 2021-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.CharField(max_length=100, verbose_name='Картинка')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('method', models.TextField(verbose_name='Способ приготовления')),
            ],
        ),
    ]
